#### Task 1 — Create Arrays

Create:

1. 1D array from 1–10
2. 2D array of shape (3,3)
3. Float array
4. Boolean array

Print:

- shape
- dtype
- ndim
- size

In [1]:
import numpy as np

In [3]:
# 1D array from 1-10
df1 = np.array([1,2,3,4,5,6,7,8,9,10])

# 2D array of shape (3,3)
df2 = np.array([[1,2,3],[1,2,3],[1,3,5]])

# Float array
df3 = np.array([1,2,3], dtype = float)

# Boolean array
df4 = np.array([True, False])

## shape
print("df1 shape", df1.shape)
print("df2 shape", df2.shape)
print("df3 shape", df3.shape)
print("df4 shape", df4.shape)

## dtype
print("df1 data type", df1.dtype)
print("df2 data type", df2.dtype)
print("df3 data type", df3.dtype)
print("df4 data type", df4.dtype)

## ndim
print("df1 n dimension", df1.ndim)
print("df2 n dimension", df2.ndim)
print("df3 n dimension", df3.ndim)
print("df4 n dimension", df4.ndim)

## size
print("df1 size", df1.size)
print("df2 size", df2.size)
print("df3 size", df3.size)
print("df4 size", df4.size)



df1 shape (10,)
df2 shape (3, 3)
df3 shape (3,)
df4 shape (2,)
df1 data type int32
df2 data type int32
df3 data type float64
df4 data type bool
df1 n dimension 1
df2 n dimension 2
df3 n dimension 1
df4 n dimension 1
df1 size 10
df2 size 9
df3 size 3
df4 size 2


#### Task 2 — Reshape Practice

Create:

[1,2,3,4,5,6,7,8,9,10,11,12]

Reshape into:

- (3,4)
- (4,3)
- (2,6)

Then:

flatten it back

In [4]:
df = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
df11 = df.reshape(3,4)
df12 = df.reshape(3,4)
df13 = df.reshape(2,6)

print(f"df11: {df11}\n")
print(f"df12: {df12}\n")
print(f"df13: {df13}\n")

print(f"df11 flatten: {df11.flatten}")
print(f"df12 flatten: {df12.flatten}")
print(f"df13 flatten: {df13.flatten}")

df11: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

df12: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

df13: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

df11 flatten: <built-in method flatten of numpy.ndarray object at 0x000001B8503D1350>
df12 flatten: <built-in method flatten of numpy.ndarray object at 0x000001B8503D1410>
df13 flatten: <built-in method flatten of numpy.ndarray object at 0x000001B8503D1470>


#### Task 3 — Indexing & Slicing

Given:

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

Do these:

- Print 50
- Print first row
- Print second column
- Print last row
- Print:
[[50,60],
 [80,90]]

In [13]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[1:2,1:2])
print(arr[0,:])
print(arr[:,1])
print(arr[2,:])
print(arr[1:3,1:3])

[[50]]
[10 20 30]
[20 50 80]
[70 80 90]
[[50 60]
 [80 90]]


#### Task 4 — Filter Data

Given:

marks = np.array([35,90,67,20,80,45])

Do:

- Print marks > 50
- Print failed students (<40)
- Replace all marks < 40 with 0
- Count students passed

In [17]:
marks = np.array([35,90,67,20,80,45])

print(marks[marks>50])
print(f"Print Failed Students {marks[marks<40]}")
marks[marks<40] = 0
print(f"Updated Marks:", marks)
passed_count = np.sum(marks >= 40)
print(f"No. of students passed: {passed_count}") 

[90 67 80]
Print Failed Students [35 20]
Updated Marks: [ 0 90 67  0 80 45]
No. of students passed: 4


#### Task 5 — Even/Odd Filtering

Create array from 1–20.

Print:

- even numbers
- odd numbers
- numbers divisible by 3

using boolean masking ONLY.

In [18]:
df = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
even_arr = df[df%2==0]
print(f"Even Number: {even_arr}")
odd_arr = df[df%2!=0]
print(f"Odd Number: {odd_arr}")
divisble_by_3 = df[df%3==0]
print(f"Divisble by 3: {divisble_by_3}")

Even Number: [ 2  4  6  8 10 12 14 16 18 20]
Odd Number: [ 1  3  5  7  9 11 13 15 17 19]
Divisble by 3: [ 3  6  9 12 15 18]


#### Task 6 — Scalar Broadcasting

Given:

arr = np.array([
    [1,2,3],
    [4,5,6]
])

Do:

- Add 10 to every element
- Multiply every element by 5
- Square every element

WITHOUT loops.

In [22]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr + 10)
print(arr * 5)
print(arr ** 2)

[[11 12 13]
 [14 15 16]]
[[ 5 10 15]
 [20 25 30]]
[[ 1  4  9]
 [16 25 36]]


#### Task 7 — Array Broadcasting

Given:

arr = np.array([
    [1,2,3],
    [4,5,6]
])

vec = np.array([10,20,30])

Add:

vec to every row

Then explain:

WHY broadcasting works here

In [23]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

vec = np.array([10,20,30])
print(arr + vec)

[[11 22 33]
 [14 25 36]]


#### Task 8 — Matrix Multiplication

Create:

A = 2x2 matrix
B = 2x2 matrix

Do:

Matrix multiplication using:
- np.dot()
- @ operator
- Element-wise multiplication using: *

Explain difference.

In [26]:
a = np.array([
    [1,2],
    [4,5]
])

b = arr = np.array([
    [1,2],
    [4,5]
])

print(np.dot(a,b))
print(a@b)
print(a*b)

[[ 9 12]
 [24 33]]
[[ 9 12]
 [24 33]]
[[ 1  4]
 [16 25]]
