#### Task 1 — Create Arrays

Create:

1. 1D array from 1–10
2. 2D array of shape (3,3)
3. Float array
4. Boolean array

Print:

- shape
- dtype
- ndim
- size

In [2]:
import numpy as np

In [3]:
# 1D array from 1-10
df1 = np.array([1,2,3,4,5,6,7,8,9,10])

# 2D array of shape (3,3)
df2 = np.array([[1,2,3],[1,2,3],[1,3,5]])

# Float array
df3 = np.array([1,2,3], dtype = float)

# Boolean array
df4 = np.array([True, False])

## shape
print("df1 shape", df1.shape)
print("df2 shape", df2.shape)
print("df3 shape", df3.shape)
print("df4 shape", df4.shape)

## dtype
print("df1 data type", df1.dtype)
print("df2 data type", df2.dtype)
print("df3 data type", df3.dtype)
print("df4 data type", df4.dtype)

## ndim
print("df1 n dimension", df1.ndim)
print("df2 n dimension", df2.ndim)
print("df3 n dimension", df3.ndim)
print("df4 n dimension", df4.ndim)

## size
print("df1 size", df1.size)
print("df2 size", df2.size)
print("df3 size", df3.size)
print("df4 size", df4.size)



df1 shape (10,)
df2 shape (3, 3)
df3 shape (3,)
df4 shape (2,)
df1 data type int32
df2 data type int32
df3 data type float64
df4 data type bool
df1 n dimension 1
df2 n dimension 2
df3 n dimension 1
df4 n dimension 1
df1 size 10
df2 size 9
df3 size 3
df4 size 2


#### Task 2 — Reshape Practice

Create:

[1,2,3,4,5,6,7,8,9,10,11,12]

Reshape into:

- (3,4)
- (4,3)
- (2,6)

Then:

flatten it back

In [4]:
df = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
df11 = df.reshape(3,4)
df12 = df.reshape(3,4)
df13 = df.reshape(2,6)

print(f"df11: {df11}\n")
print(f"df12: {df12}\n")
print(f"df13: {df13}\n")

print(f"df11 flatten: {df11.flatten}")
print(f"df12 flatten: {df12.flatten}")
print(f"df13 flatten: {df13.flatten}")

df11: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

df12: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

df13: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

df11 flatten: <built-in method flatten of numpy.ndarray object at 0x00000210E47E6550>
df12 flatten: <built-in method flatten of numpy.ndarray object at 0x00000210E47E65B0>
df13 flatten: <built-in method flatten of numpy.ndarray object at 0x00000210E47E6610>


#### Task 3 — Indexing & Slicing

Given:

arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

Do these:

- Print 50
- Print first row
- Print second column
- Print last row
- Print:
[[50,60],
 [80,90]]

In [5]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[1:2,1:2])
print(arr[0,:])
print(arr[:,1])
print(arr[2,:])
print(arr[1:3,1:3])

[[50]]
[10 20 30]
[20 50 80]
[70 80 90]
[[50 60]
 [80 90]]


#### Task 4 — Filter Data

Given:

marks = np.array([35,90,67,20,80,45])

Do:

- Print marks > 50
- Print failed students (<40)
- Replace all marks < 40 with 0
- Count students passed

In [6]:
marks = np.array([35,90,67,20,80,45])

print(marks[marks>50])
print(f"Print Failed Students {marks[marks<40]}")
marks[marks<40] = 0
print(f"Updated Marks:", marks)
passed_count = np.sum(marks >= 40)
print(f"No. of students passed: {passed_count}") 

[90 67 80]
Print Failed Students [35 20]
Updated Marks: [ 0 90 67  0 80 45]
No. of students passed: 4


#### Task 5 — Even/Odd Filtering

Create array from 1–20.

Print:

- even numbers
- odd numbers
- numbers divisible by 3

using boolean masking ONLY.

In [7]:
df = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
even_arr = df[df%2==0]
print(f"Even Number: {even_arr}")
odd_arr = df[df%2!=0]
print(f"Odd Number: {odd_arr}")
divisble_by_3 = df[df%3==0]
print(f"Divisble by 3: {divisble_by_3}")

Even Number: [ 2  4  6  8 10 12 14 16 18 20]
Odd Number: [ 1  3  5  7  9 11 13 15 17 19]
Divisble by 3: [ 3  6  9 12 15 18]


#### Task 6 — Scalar Broadcasting

Given:

arr = np.array([
    [1,2,3],
    [4,5,6]
])

Do:

- Add 10 to every element
- Multiply every element by 5
- Square every element

WITHOUT loops.

In [8]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr + 10)
print(arr * 5)
print(arr ** 2)

[[11 12 13]
 [14 15 16]]
[[ 5 10 15]
 [20 25 30]]
[[ 1  4  9]
 [16 25 36]]


#### Task 7 — Array Broadcasting

Given:

arr = np.array([
    [1,2,3],
    [4,5,6]
])

vec = np.array([10,20,30])

Add:

vec to every row

Then explain:

WHY broadcasting works here

In [9]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

vec = np.array([10,20,30])
print(arr + vec)

[[11 22 33]
 [14 25 36]]


#### Task 8 — Matrix Multiplication

Create:

A = 2x2 matrix
B = 2x2 matrix

Do:

Matrix multiplication using:
- np.dot()
- @ operator
- Element-wise multiplication using: *

Explain difference.

In [10]:
a = np.array([
    [1,2],
    [4,5]
])

b = arr = np.array([
    [1,2],
    [4,5]
])

print(np.dot(a,b))
print(a@b)
print(a*b)

[[ 9 12]
 [24 33]]
[[ 9 12]
 [24 33]]
[[ 1  4]
 [16 25]]


#### Task 9 — Transpose

Create:

3x2 matrix

Find transpose.

Print:

- original shape
- transpose shape

In [12]:
dff = np.array([[1,2],
                [2,3],
                [8,9]])
print(f"Original Matrix: {dff}")
dff_transpose = dff.T
print(f"Transpose Matrix: {dff_transpose}")
print(f"Original Matrix Size: {dff.shape}")
print(f"Transpose Matrix Size: {dff_transpose.shape}")

Original Matrix: [[1 2]
 [2 3]
 [8 9]]
Transpose Matrix: [[1 2 8]
 [2 3 9]]
Original Matrix Size: (3, 2)
Transpose Matrix Size: (2, 3)


#### Task 10 — Matrix Statistics

Generate random matrix:

4x4

Find:

- sum
- mean
- max
- min
- row-wise sum
- column-wise sum

In [18]:
df = np.array([[1,2,3,4],
               [5,6,7,8], 
               [8,4,6,7],
               [90,34,6,7]])
sum = np.sum(df)
print(f"Sum: {sum}")
mean = np.mean(df)
print(f"mean: {mean}")
maxi = np.max(df)
print(f"Max: {maxi}")
mini = np.min(df)
print(f"Min: {mini}")

row_wise_sum = np.sum(df, axis = 1)
col_wise_sum = np.sum(df, axis = 0)
print(f"Row Wise Sum: {row_wise_sum}")
print(f"Column Wise Sum: {col_wise_sum}")

Sum: 198
mean: 12.375
Max: 90
Min: 1
Row Wise Sum: [ 10  26  25 137]
Column Wise Sum: [104  46  22  26]


#### ask 11 — Random Arrays

Generate:

- Random integers
- Random float matrix
- Random array between 50–100

In [24]:
print(f"Random integer integers: {np.random.randint(1,20, size = (2,6))}")
print(f"Random float integers: {np.random.rand(1,20)}")
print(f"Random array bw 50-100: {np.random.randint(50,100, size = (2,6))}")



Random integer integers: [[ 8 10 18 18 17 10]
 [13  4  4  4  2 15]]
Random float integers: [[0.97334244 0.32494758 0.28351467 0.93160356 0.2880929  0.38577496
  0.99824896 0.57326943 0.67593625 0.28565193 0.36124732 0.29486686
  0.95062334 0.77819332 0.7557194  0.66374925 0.18683337 0.35412294
  0.46808378 0.47043985]]
Random array bw 50-100: [[59 57 68 66 99 71]
 [86 77 73 96 57 80]]


#### ask 12 — Seed

Use:

np.random.seed(42)

Generate random arrays twice.

Check:

why output same

Then explain:

why reproducibility important in ML

In [26]:
print(f"Random Array 1: {np.random.seed(42)}")
print(f"Random Array 2: {np.random.seed(42)}")

Random Array 1: None
Random Array 2: None


#### ask 13 — Replace Values

Given:

arr = np.array([1,5,8,10,3,7])

Replace:

values > 5 → 100

WITHOUT loops.

In [28]:
arr = np.array([1,5,8,10,3,7])
arr[arr>5] = 100
print(f"Replace number array: {arr}")

Replace number array: [  1   5 100 100   3 100]


#### ask 14 — Normalize Data

Given:

arr = np.array([10,20,30,40,50])

Normalize using formula:

x
norm
	​

=
x
max
	​

−x
min
	​

x−x
min
	​

	​


This is REAL ML preprocessing.

In [32]:
arr = np.array([1,5,8,10,3,7])

arr_norm = (arr - arr.min()) / (arr.max() - arr.min())
print(arr_norm)

[0.         0.44444444 0.77777778 1.         0.22222222 0.66666667]


#### Task 15 — Find Unique Values

Given:

arr = np.array([1,1,2,3,3,4,5,5])

Find:

- unique values
- count of unique values

In [35]:
unique_values, counts = np.unique(arr, return_counts=True)
print(f"Unique values: {unique_values}")
print(f"Count of unique values: {counts}")

Unique values: [ 1  3  5  7  8 10]
Count of unique values: [1 1 1 1 1 1]


#### Task 16 — Student Marks Analyzer

Create NumPy array of student marks.

Find:

- average marks
- topper marks
- failed students
- percentage above 75

In [37]:
# Student marks
marks = np.array([78, 45, 90, 67, 34, 88, 76, 55, 92, 40])

# 1. Average marks
average_marks = np.mean(marks)
print("Average Marks:", average_marks)

# 2. Topper Marks
topper_marks = np.max(marks)
print("Topper Marks:", topper_marks)

# 3. Failed Students
failed_students = np.min(marks)
print("Failed students:", failed_students)

#4. Percentage above 75%
above_75 = marks[marks>75]
print("above 75%:", above_75)

Average Marks: 66.5
Topper Marks: 92
Failed students: 34
above 75%: [78 90 88 76 92]


#### Task 18 — Manual Matrix Multiplication

Implement matrix multiplication:

using loops ONLY

Then compare with:

np.dot()

In [39]:
# Matrices
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

# Dimensions
rows_A = len(A)
cols_A = len(A[0])

rows_B = len(B)
cols_B = len(B[0])

result = [[0 for _ in range(cols_B)] for _ in range(rows_A)]

for i in range(rows_A):
    for j in range(cols_B):
        for k in range(cols_A):
            result[i][j] += A[i][k] *  B[k][j]

print("Manual MAtrix Multiplication: ")
for row in result:
    print(row)

numpy_result = np.dot(A,B)

print("Using np.dot()")
print(numpy_result)


Manual MAtrix Multiplication: 
[19, 22]
[43, 50]
Using np.dot()
[[19 22]
 [43 50]]
